export const PERFORM_LOGIN_BEGIN = 'PERFORM_LOGIN_BEGIN';
export const PERFORM_LOGIN_SUCCESS = 'PERFORM_LOGIN_SUCCESS';
export const PERFORM_LOGIN_FAILURE = 'PERFORM_LOGIN_FAILURE';
export const PERFORM_REGISTRATION_BEGIN = 'PERFORM_REGISTRATION_BEGIN';
export const PERFORM_REGISTRATION_SUCCESS = 'PERFORM_REGISTRATION_SUCCESS';
export const PERFORM_REGISTRATION_FAILURE = 'PERFORM_REGISTRATION_FAILURE';