export const FETCH_MOVIES_BEGIN = 'FETCH_MOVIES_BEGIN';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const FETCH_DIRECTORS_BEGIN = 'FETCH_DIRECTORS_BEGIN';
export const FETCH_DIRECTORS_SUCCESS = 'FETCH_DIRECTORS_SUCCESS';
export const FETCH_DIRECTORS_FAILURE = 'FETCH_DIRECTORS_FAILURE';